<!-- Reference implementation -->
<template>
  <div>
    <!-- 
      By default this is 20px. We want to make the timeline come close to the edge to save space
    hence made it 3px
    This controls the space between edge of the card and the line that shows the dots
    -->
    <el-card class="box-card" :body-style="{ paddingLeft: '3px' }">
      <div slot="header" class="clearfix">
        <span :tabindex="cfPosInArCardsInPtsOfViewLayer * 100 + 1" @keyup="mfKeyPress($event, 'header')"
          >Phone Number</span
        >
        <el-button-group style="float: right">
          <el-button
            style="padding: 3px"
            plain
            tabindex="-1"
            @click="mxOpenAddCtInEditLayer"
            class="el-icon-circle-plus-outline"
          ></el-button>
          <el-button style="padding: 3px" plain tabindex="-1" @click="mxOpenMultiEditCtInEditLayer">M</el-button>
          <el-button
            style="padding: 3px"
            plain
            tabindex="-1"
            @click="mxOpenDDialog"
            class="el-icon-document-delete"
          ></el-button>
          <el-button
            style="padding: 3px"
            plain
            tabindex="-1"
            @click="mxOpenTrashCanCtInEditLayer"
            class="el-icon-delete"
          ></el-button>
        </el-button-group>
      </div>
      <!-- explanation of following params:
            1. padding-inline-start: 20px
              This is the space between edge of the card and the line that shows the dots
              By default this is 40px 
            2. $id   
              This is incremental number generated by vuex-orm 
        -->
      <el-timeline style="padding-inline-start: 20px">
        <el-timeline-item
          v-for="row in cfArOfRemForDisplayInTable"
          :key="row.id"
          :timestamp="row.createdAt"
          :type="row.type"
          :tabindex="cfPosInArCardsInPtsOfViewLayer * 100 + 2"
          @keyup.native="mfKeyPress($event, row.id, row.description)"
        >
          {{ row.description }}
          <el-button-group style="float: right">
            <el-button
              type="primary"
              size="mini"
              style="padding: 3px"
              plain
              tabindex="-1"
              @click="mxOpenEditCtInEditLayer(row.id)"
              class="el-icon-edit"
            ></el-button>
            <el-button
              type="warning"
              size="mini"
              style="padding: 3px"
              plain
              tabindex="-1"
              @click="mxOpenDPrompt(row.id)"
              class="el-icon-document-delete"
            ></el-button>
          </el-button-group>
        </el-timeline-item>
      </el-timeline>
    </el-card>
  </div>
</template>

<script>
import clientTbl from '../db/client-side/structure/table.js'
import clInvokeMixin from './cl-invoke-mixin.js'
import clientTblOfRightSideCards from '@/components/non-temporal/search-phrases/db/client-side/structure/table-of-cards-chosen-by-user-to-display.js'

export default {
  mixins: [clInvokeMixin],
  data() {
    return {}
  },
  computed: {
    cfPosInArCardsInPtsOfViewLayer() {
      const arFromClientTbl = clientTblOfRightSideCards.query().where('name', 'reminders').get()
      return arFromClientTbl['clientSideUniqRowId']
    },
    cfArOfRemForDisplayInTable() {
      const arFromClientTbl = clientTbl.fnGetPresentUniqueUuidNotEmptyRows('description')

      /*  Q) Should this function return the array it gets from ORM or modify the array?
              Option1: Return ORM array
                  -ves:
                    1. Created at needs to be made inside the template
                    2. Making pager would be harder
                  +ves:
                    No need to run the for loop
      */

      const arphoneNumberForDisplay = []
      let obj = {}
      if (arFromClientTbl.length) {
        let date = ''
        for (let i = 0; i < arFromClientTbl.length; i++) {
          obj = {}
          obj.description = arFromClientTbl[i].description
          // For date format ref: /cts/temporal/1-framework/view-layer/timeline-ct.vue:53
          date = new Date(arFromClientTbl[i].ROW_START)
          obj.createdAt = date.toLocaleString('default', { month: 'long' }) + '-' + date.getDate()
          obj.vnRowStateInSession = arFromClientTbl[i].vnRowStateInSession
          obj.uuid = arFromClientTbl[i].serverSideRowUuid
          obj.id = arFromClientTbl[i].clientSideUniqRowId
          arphoneNumberForDisplay.push(obj)
        }
      }
      return arphoneNumberForDisplay
    },
  },
  mounted() {},
  methods: {
    mfKeyPress(e, rowId, pRemDesc) {
      console.log(e, rowId)
      if (rowId === 'header') {
        if (e.code === 'KeyA') {
          this.mxOpenAddCtInEditLayer()
        }
        if (e.code === 'KeyM') {
          this.mxOpenMultiEditCtInEditLayer()
        }
        if (e.code === 'KeyD') {
          this.mxOpenDDialog()
        }
        if (e.code === 'KeyX') {
          this.mxOpenTrashCanCtInEditLayer()
        }
      } else {
        if (e.code === 'KeyC') {
          this.mxOpenEditCtInEditLayer(rowId)
        }
        if (e.code === 'KeyD') {
          this.mxOpenDPrompt(rowId)
        }
      }
    },
  },
}
</script>
