<!-- Reference implementation -->
<template>
  <div>
    <!-- 
      By default this is 20px. We want to make the timeline come close to the edge to save space
    hence made it 3px
    This controls the space between edge of the card and the line that shows the dots
    -->
    <el-card class="box-card" :body-style="{ paddingLeft: '3px' }">
      <div slot="header" class="clearfix">
        <span :tabindex="cfPosInArCardsInPtsOfVl * 100 + 1" @keyup="mfKeyPress($event, 'header')"
          >Reminders</span
        >
        <el-button-group style="float: right;">
          <el-button style="padding: 3px;" type="success" plain tabindex="-1" @click="mxOpenACtInCl"
            >A</el-button
          >
          <el-button style="padding: 3px;" type="primary" plain tabindex="-1" @click="mxOpenMCtInCl"
            >M</el-button
          >
          <el-button style="padding: 3px;" type="warning" plain tabindex="-1" @click="mxOpenDDialog"
            >D</el-button
          >
          <el-button style="padding: 3px;" type="info" plain tabindex="-1" @click="mxOpenXCtInCl"
            >X</el-button
          >
        </el-button-group>
      </div>
      <!-- explanation of following params:
            1. padding-inline-start: 20px
              This is the space between edge of the card and the line that shows the dots
              By default this is 40px 
            2. $id   
              This is incremental number generated by vuex-orm 
        -->
      <el-timeline style="padding-inline-start: 20px;">
        <el-timeline-item
          v-for="row in cfArOfRemForDisplayInTable"
          :key="row.id"
          :timestamp="row.createdAt"
          :type="row.type"
          :tabindex="cfPosInArCardsInPtsOfVl * 100 + 2"
          @keyup.native="mfKeyPress($event, row.id, row.remDesc)"
        >
          {{ row.remDesc }}
          <el-button-group style="float: right;">
            <el-button
              type="primary"
              size="mini"
              style="padding: 3px;"
              plain
              tabindex="-1"
              @click="mxOpenCCtInCl(row.id)"
              >C</el-button
            >
            <el-button
              type="warning"
              size="mini"
              style="padding: 3px;"
              plain
              tabindex="-1"
              @click="mxOpenDPrompt(row.id)"
              >D</el-button
            >
          </el-button-group>
        </el-timeline-item>
      </el-timeline>
    </el-card>
  </div>
</template>

<script>
import clInvokeMixin from './cl-invoke-mixin.js'
import ormRem from '@/cts/spi/1t-Mr1f/rem/db/vuex-orm/rem.js'

export default {
  mixins: [clInvokeMixin],
  data() {
    return {}
  },
  computed: {
    cfPosInArCardsInPtsOfVl() {
      const arCardsInCsOfVl = this.$store.state.vstObjCardsInCsOfVl.arCardsInCsOfVl
      const obj = arCardsInCsOfVl.find((x) => x.label === 'reminders')
      const idx = arCardsInCsOfVl.indexOf(obj)
      return idx
    },
    cfArOfRemForDisplayInTable() {
      const arFromOrm = ormRem.getValidUniqueUuidNotEmptyRows('remDesc')

      /*  Q) Should this function return the array it gets from ORM or modify the array?
              Option1: Return ORM array
                  -ves:
                    1. Created at needs to be made inside the template
                    2. Making pager would be harder
                  +ves:
                    No need to run the for loop
      */

      const arRemsForDisplay = []
      let obj = {}
      if (arFromOrm.length) {
        let date = ''
        for (let i = 0; i < arFromOrm.length; i++) {
          obj = {}
          obj.remDesc = arFromOrm[i].remDesc
          // For date format ref: /cts/spi/1t-Mr1f/rem/vl/timeline.vue:53
          date = new Date(arFromOrm[i].ROW_START)
          obj.createdAt = date.toLocaleString('default', { month: 'long' }) + '-' + date.getDate()
          obj.vnRowStateInSession = arFromOrm[i].vnRowStateInSession
          obj.uuid = arFromOrm[i].uuid
          obj.id = arFromOrm[i].id
          arRemsForDisplay.push(obj)
        }
      }
      return arRemsForDisplay
    },
  },
  mounted() {},
  methods: {
    mfKeyPress(e, rowId, pRemDesc) {
      console.log(e, rowId)
      if (rowId === 'header') {
        if (e.code === 'KeyA') {
          this.mxOpenACtInCl()
        }
        if (e.code === 'KeyM') {
          this.mxOpenMCtInCl()
        }
        if (e.code === 'KeyD') {
          this.mxOpenDDialog()
        }
        if (e.code === 'KeyX') {
          this.mxOpenXCtInCl()
        }
      } else {
        if (e.code === 'KeyC') {
          this.mxOpenCCtInCl(rowId)
        }
        if (e.code === 'KeyD') {
          this.mxOpenDPrompt(rowId)
        }
      }
    },
  },
}
</script>
