use sc_psych_review_of_systems;

DROP TABLE IF EXISTS `psych_review_of_systems`;

CREATE TABLE `psych_review_of_systems` (
  `serverSideRowUuid` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `ptUuid` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `subjective` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `depressive_mood` int(11) DEFAULT NULL,
  `depressive_interest` int(11) DEFAULT NULL,
  `depressive_sleep` int(11) DEFAULT NULL,
  `depressive_esteem` int(11) DEFAULT NULL,
  `depressive_energy` int(11) DEFAULT NULL,
  `depressive_conc` int(11) DEFAULT NULL,
  `depressive_appetite` int(11) DEFAULT NULL,
  `depressive_retardation` int(11) DEFAULT NULL,
  `depressive_suicidal` int(11) DEFAULT NULL,
  `gateway_depressed` int(11) DEFAULT NULL,
  `gateway_energetic` int(11) DEFAULT NULL,
  `gateway_interest` int(11) DEFAULT NULL,
  `gateway_mood` int(11) DEFAULT NULL,
  `gateway_irritable` int(11) DEFAULT NULL,
  `gateway_difficult` int(11) DEFAULT NULL,
  `mania_mood` int(11) DEFAULT NULL,
  `mania_irritable` int(11) DEFAULT NULL,
  `mania_energy` int(11) DEFAULT NULL,
  `mania_sleep` int(11) DEFAULT NULL,
  `mania_talking` int(11) DEFAULT NULL,
  `mania_racing` int(11) DEFAULT NULL,
  `mania_distractibility` int(11) DEFAULT NULL,
  `mania_risk` int(11) DEFAULT NULL,
  `psychosis_delusions` int(11) DEFAULT NULL,
  `psychosis_hallucinations` int(11) DEFAULT NULL,
  `psychosis_speech` int(11) DEFAULT NULL,
  `psychosis_behavior` int(11) DEFAULT NULL,
  `psychosis_negativeSx` int(11) DEFAULT NULL,
  `adhd_inattention` int(11) DEFAULT NULL,
  `adhd_hyperactivity` int(11) DEFAULT NULL,
  `adhd_careless` int(11) DEFAULT NULL,
  `adhd_problem` int(11) DEFAULT NULL,
  `adhd_poor` int(11) DEFAULT NULL,
  `adhd_fails` int(11) DEFAULT NULL,
  `adhd_difficulty` int(11) DEFAULT NULL,
  `adhd_reluctant` int(11) DEFAULT NULL,
  `adhd_loses` int(11) DEFAULT NULL,
  `adhd_distracted` int(11) DEFAULT NULL,
  `adhd_forgetful` int(11) DEFAULT NULL,
  `adhd_fidgets` int(11) DEFAULT NULL,
  `adhd_leaves` int(11) DEFAULT NULL,
  `adhd_feels` int(11) DEFAULT NULL,
  `adhd_unable` int(11) DEFAULT NULL,
  `adhd_seems` int(11) DEFAULT NULL,
  `adhd_talks` int(11) DEFAULT NULL,
  `adhd_blurts` int(11) DEFAULT NULL,
  `adhd_difficulty_waiting` int(11) DEFAULT NULL,
  `adhd_interrupts` int(11) DEFAULT NULL,
  `recordChangedByUuid` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `recordChangedFromIPAddress` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `recordChangedFromSection` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT 'patientFile',
   PRIMARY KEY (`serverSideRowUuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;
