<!-- Reference implementation -->
<template>
  <!-- 
      By default this is 20px. We want to make the timeline come close to the edge to save space
    hence made it 3px
    This controls the space between edge of the card and the line that shows the dots
    -->
  <el-card class="box-card sc-service-statement-all-content" :body-style="{ paddingLeft: '3px' }" shadow="hover">
    <div slot="header" class="clearfix">
      <span :tabindex="cfPosInArCardsInPtsOfViewLayer * 100 + 1" @keyup="mfKeyPress($event, 'header')">{{
        propFormDef.id
      }}</span>
      <el-button-group style="float: right">
        <el-button
          style="padding: 3px"
          plain
          tabindex="-1"
          @click="mxOpenAddCtInEditLayer"
          class="el-icon-circle-plus-outline"
        ></el-button>
        <el-button style="padding: 3px" plain tabindex="-1" @click="mxOpenMultiEditCtInEditLayer">M</el-button>
        <el-button
          style="padding: 3px"
          plain
          tabindex="-1"
          @click="mxOpenDDialog"
          class="el-icon-document-delete"
        ></el-button>
        <el-button
          style="padding: 3px"
          plain
          tabindex="-1"
          @click="mxOpenTrashCanCtInEditLayer"
          class="el-icon-delete"
        ></el-button>
      </el-button-group>
    </div>
    <!-- explanation of following params:
            1. padding-inline-start: 20px
              This is the space between edge of the card and the line that shows the dots
              By default this is 40px 
            2. $id   
              This is incremental number generated by vuex-orm 
        -->
    <el-timeline style="padding-inline-start: 20px">
      <el-timeline-item
        v-for="row in cfArOfRemForDisplayInTable"
        :key="row.id"
        :timestamp="row.createdAt"
        :type="row.type"
        :tabindex="cfPosInArCardsInPtsOfViewLayer * 100 + 2"
        @keyup.native="mfKeyPress($event, row.id, row.description)"
      >
        <div v-for="(propFieldObj, id) in propFormDef.fields" :key="id">
          {{ row[propFieldObj.fieldNameInDb] }}
        </div>
        <el-button-group style="float: right">
          <el-button
            size="mini"
            style="padding: 3px"
            plain
            tabindex="-1"
            @click="mxOpenEditCtInEditLayer(row.clientSideUniqRowId)"
            class="el-icon-edit"
          ></el-button>
          <el-button
            size="mini"
            style="padding: 3px"
            plain
            tabindex="-1"
            @click="mxOpenDPrompt(row.clientSideUniqRowId)"
            class="el-icon-document-delete"
          ></el-button>
        </el-button-group>
      </el-timeline-item>
    </el-timeline>
    <ctActOnSocketMessages></ctActOnSocketMessages>
  </el-card>
</template>

<script>
import ctActOnSocketMessages from '../change/act-on-socket-messages-from-server-ct.vue'
import clInvokeMixin from './cl-invoke-mixin.js'
import clientTblOfRightSideCards from '@/components/non-temporal/search-phrases/db/client-side/structure/table-of-cards-chosen-by-user-to-display.js'

import allClientTbls from '../all-client-tables.js'

export default {
  components: { ctActOnSocketMessages },

  mixins: [clInvokeMixin],
  data() {
    return {}
  },
  props: {
    propFormDef: {
      type: Object,
      required: true,
      validator: function (obj) {
        // id and fields must be present
        if (obj.id) {
          if (obj.fields) {
            if (Object.keys(allClientTbls).includes(obj.id)) {
              return true
            }
          }
        }

        return false
      },
    },
  }, // firstProp is the ClientIdOfRowToChange
  computed: {
    cfPosInArCardsInPtsOfViewLayer() {
      const arFromClientTbl = clientTblOfRightSideCards.query().where('name', this.propFormDef.id).get()
      return arFromClientTbl['clientSideUniqRowId']
    },
    cfArOfRemForDisplayInTable() {
      const arFromClientTbl = allClientTbls[this.propFormDef.id].fnGetPresentUniqueUuidNotEmptyRows(
        this.propFormDef.fieldForCheckingIfRowIsEmpty
      )

      /*  Q) Should this function return the array it gets from ORM or modify the array?
              Option1: Return ORM array
                  -ves:
                    1. Created at needs to be made inside the template
                    2. Making pager would be harder
                  +ves:
                    No need to run the for loop
      */

      return arFromClientTbl
    },
  },
  mounted() {},
  methods: {
    mfKeyPress(e, rowId, pRemDesc) {
      console.log(e, rowId)
      if (rowId === 'header') {
        if (e.code === 'KeyA') {
          this.mxOpenAddCtInEditLayer()
        }
        if (e.code === 'KeyM') {
          this.mxOpenMultiEditCtInEditLayer()
        }
        if (e.code === 'KeyD') {
          this.mxOpenDDialog()
        }
        if (e.code === 'KeyX') {
          this.mxOpenTrashCanCtInEditLayer()
        }
      } else {
        if (e.code === 'KeyC') {
          this.mxOpenEditCtInEditLayer(rowId)
        }
        if (e.code === 'KeyD') {
          this.mxOpenDPrompt(rowId)
        }
      }
    },
  },
}
</script>
<style>
/* Generation ->
==============
                                       .sc-reminder-all-content
 Generation 1                                      |
==============                     _________________________________
                                  |                                |
                    .sc-reminder-all-content-header                |
 Generatiobn 2                                                     |
                                    _______________________________|
                                  |
                  .sc-reminder-all-content-body
==============                    |
                                  |
                   .sc-reminder-individual-card
Generatiobn 3                     |
                       ________________________________________________________________________________
                      |                                 |                                             |
        .sc-reminder-individual-card-content    .sc-reminder-individual-card-info-icon           .sc-reminder-individual-card-delete-icon

==============
*/

/* Generation Level 1 */
.sc-reminder-all-content .el-card__header {
  /* Goal: Manage Distance from border to content in header*/
  padding: 10px !important;
}

.sc-reminder-all-content .el-card__body {
  /* Goal: Manage  Distance from border to content in body*/
  padding: 10px !important;
}

/* Generation Level 2 / Child 1 == Goal: Header icon management */

/* When anywhere inside the card make the action icons in the card header -> level 1 visual */
.el-card:hover .sc-reminder-all-content-header .el-button-group {
  display: inline-block !important;
}

/* When inside the card header make the action icons in the card header -> level 2 visual */
.el-card__header:hover .sc-reminder-all-content-header .el-icon-edit {
  color: #67c23a !important;
  font-size: 1.5rem;
}
.el-card__header:hover .sc-reminder-all-content-header .el-icon-s-grid {
  color: #409eff !important;
}
.el-card__header:hover .sc-reminder-all-content-header .el-icon-document-delete {
  color: #f56c6c !important;
}
.el-card__header:hover .sc-reminder-all-content-header .el-icon-delete {
  color: #909399 !important;
}

/* Generation Level 2 / Child 2 */

/* Goal: When less space display 1 card in a row. When more space display 100 cards in a row. */
.sc-reminder-all-content-body {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  /* Some other grid-template-columns options are :
  grid-template-columns: repeat(auto-fit, minmax(32rem, 1fr));
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  grid-template-columns: repeat(auto-fit, max(200px)); compared to minmax(200px, 1fr) there is more magin between cols and less content fits.
  */
  grid-gap: 1px;
  grid-auto-flow: row; /* This is default value */
  margin: 1px;
}

/* Generation Level 3 */

/* Goal: Margin and padding of individual card */

.sc-reminder-individual-card {
  cursor: pointer;
  overflow-wrap: break-word;
  position: relative;
  margin: 1px;
  padding: 10px 1px 1px !important;
}

/* Goal: Header icon management  */
.el-card:hover .sc-reminder-individual-card .el-button-group {
  display: inline-block !important;
  position: absolute;
  top: 0px;
  right: 0px;
}

.sc-reminder-individual-card:hover .el-icon-discover {
  color: #909399 !important;
}

.sc-reminder-individual-card:hover .el-icon-circle-close {
  color: #f56c6c !important;
  font-size: 1.5rem;
}
</style>
