#!/bin/bash
echo "For this script to run redis-server must be installed"
echo ""
echo "On mac"
echo "======"
echo "The command I gave was > brew install redis"
echo ""
echo "On windows"
echo "=========="
echo "Download binary from:"
echo "Option1: https://github.com/dmajkic/redis/downloads"
echo "Option2: https://github.com/microsoftarchive/redis/releases 3.0.504"
echo ""
echo "Starting redis-server"
echo "====================="
echo ""
redis-server
